[build]
command = "nx build astro"
publish = "dist/packages/astro"
ignore = "exit 1" # always say content changed

[[edge_functions]]
function = "abtest"
path = "/abtest"

[[plugins]]
package = "/packages/astro/netlify/build-plugin"
